version: '3'
services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongodb
  price-tracker:
    build: .
    container_name: price-tracker
    depends_on:
      - mongodb